---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrect
  namespace: cert-manager
type: Opaque
data:
  secret-access-key: xxxxxxxxxxxxxx

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns-issuer-aws-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "teamsmiley@gmail.com"
    privateKeySecretRef:
      name: dns-issuer-staging
    solvers:
      - dns01:
          route53:
            region: us-west-1
            accessKeyID: xxxxxxxxxxxxxx
            secretAccessKeySecretRef:
              name: aws-secrect
              key: secret-access-key

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns-issuer-aws-live
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "teamsmiley@gmail.com"
    privateKeySecretRef:
      name: dns-issuer-aws-live
    solvers:
      - dns01:
          route53:
            region: us-west-1
            accessKeyID: xxxxxxxxxxxxxx
            secretAccessKeySecretRef:
              name: aws-secrect
              key: secret-access-key
