apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  slack-token: xoxb-138023552246-2133137190339-LWciijAGdDz61fppHjQhrDYD
type: Opaque

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   annotations:
#     notifications.argoproj.io/subscribe.on-sync-succeeded.slack: my-channel1;my-channel2

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   annotations:
#     notifications.argoproj.io/subscribe.on-sync-succeeded.slack: coding
 