global:
  resolve_timeout: 1m
  slack_api_url: "https://hooks.slack.com/services/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"
route:
  receiver: "slack-notifications"
receivers:
  - name: "slack-notifications"
    slack_configs:
      - send_resolved: true
        icon_url: "https://avatars3.githubusercontent.com/u/3380462"
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] C4 Monitoring Event Notification'
        text: |-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
            *Description:* {{ .Annotations.description }}
            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
