apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-argocd-notifications
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: deploy/core/argocd/notifications/slack
    repoURL: "git@github.com:teamsmiley/argocd-c4.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
