apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-metrics-server
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  source:
    path: core/metrics-server
    repoURL: "git@github.com:teamsmiley/argocd-c4.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
